Class {
	#name : 'SysmelScheduledRegionsAndInstructionsAlgorithm',
	#superclass : 'Object',
	#instVars : [
		'regions',
		'instructions'
	],
	#category : 'Sysmel-MiddleEnd-SeaOfNodesGraph',
	#package : 'Sysmel-MiddleEnd',
	#tag : 'SeaOfNodesGraph'
}

{ #category : 'accessing' }
SysmelScheduledRegionsAndInstructionsAlgorithm >> instructions [

	^ instructions
]

{ #category : 'accessing' }
SysmelScheduledRegionsAndInstructionsAlgorithm >> instructions: anObject [

	instructions := anObject
]

{ #category : 'accessing' }
SysmelScheduledRegionsAndInstructionsAlgorithm >> regions [

	^ regions
]

{ #category : 'accessing' }
SysmelScheduledRegionsAndInstructionsAlgorithm >> regions: anObject [

	regions := anObject
]
